version: '3'

services:
  web:
    build:
      context: src/app/
      dockerfile: Dockerfile
    env_file: .env
    container_name: ${F_NAME}
    ports:
      - '${F_EXP_PORT}:${F_HID_PORT}' 

  spark:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    #command: bash -c "pip3 install numpy pyspark"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - './spark/app:/opt/bitnami/spark/app'
      - './spark/resources/data:/opt/bitnami/spark/data'
  
  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-1
    #command: bash -c "pip3 install numpy pyspark"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  
  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker-2
    #command: bash -c "pip3 install numpy pyspark"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no