version: '3'

services:
  cassandra-node1:
    image: docker.io/bitnami/cassandra:latest
    env_file: .env
    container_name: db-node1
    volumes:
      - ./config/cassandra:/docker-entrypoint-initdb.d
      - ./tmp:/bitnami/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=${C_CLUSTER_NAME}
      - CASSANDRA_SEEDS=db-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=${C_CLUSTER_PASS}
      - CASSANDRA_DATACENTER=${C_DATACENTER_NAME}
      - CASSANDRA_AUTH_ENABLED=no
    ports:
      - '${C_NODE1_EXP_PORT}:9042'
      - 7000:7000
