.PHONY: update 
update: 
	pip3 freeze > requeriments.txt 

.PHONY: setup 
setup:
	sudo docker-compose up 

.PHONY: down 
down:
	sudo docker-compose down 
	sudo docker rmi scalablerecommendsystem_web
	sudo docker system prune 
	clear

.PHONY: pull
pull:
	git pull origin main

.PHONY: push
push:
	git status 
	git add . 
	git commit -m "Generated by Makefile"
	git push origin main 