.PHONY: update 
update: 
	pip3 freeze > requeriments.txt 

.PHONY: setup 
setup:
	sudo docker-compose up

.PHONY: preprocess
preprocess:
	python3 config/preprocess/preprocess.py

.PHONY: exportdb
exportdb:
	python3 config/preprocess/store_cassandra.py

.PHONY: down 
down:
	sudo docker-compose down 
	sudo docker rmi scalablerecommendsystem_web
	sudo docker system prune 
	clear

.PHONY: pull
pull:
	git pull origin main

.PHONY: push
push:
	git status 
	git add . 
	git commit -m "Generated by Makefile"
	git push origin main 

.PHONY: bash-spark-master
bash-spark-master:
	sudo docker exec -it spark-master bash  

.PHONY: up-venv 
up-venv:
	source venv/bin/activate

.PHONY: down-venv
	deactivate

