version: '3'

services:
  #web:
  #  build:
  #    context: src/app/
  #    dockerfile: Dockerfile
  #  env_file: .env
  #  container_name: ${F_NAME}
  #  ports:
  #    - '${F_EXP_PORT}:${F_HID_PORT}' 

  spark:
    image: docker.io/bitnami/spark:3.3
    env_file: .env
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '${S_EXP_PORT_UI}:8080'
      - '${S_CONN_PORT}:7077'
    volumes:
      - './src/spark/app:/opt/bitnami/spark/app'
      - './src/spark/data:/opt/bitnami/spark/data'
  
  spark-worker-1:
    image: docker.io/bitnami/spark:3.3
    env_file: .env
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=${S_MEMORY_SET}
      - SPARK_WORKER_CORES=${S_NUM_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-2:
    image: docker.io/bitnami/spark:3.3
    env_file: .env
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=${S_MEMORY_SET}
      - SPARK_WORKER_CORES=${S_NUM_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no 

  #cassandra-node1:
    #image: docker.io/bitnami/cassandra:latest
    #env_file: .env
    #container_name: db-node1
    #volumes:
    #  - ./config/cassandra:/docker-entrypoint-initdb.d
    #environment:
    #  - CASSANDRA_CLUSTER_NAME=${C_CLUSTER_NAME}
    #  - CASSANDRA_SEEDS=db-node1
    #  - CASSANDRA_PASSWORD_SEEDER=yes
    #  - CASSANDRA_PASSWORD=${C_CLUSTER_PASS}
    #  - CASSANDRA_DATACENTER=${C_DATACENTER_NAME}
    #  - CASSANDRA_AUTH_ENABLED=no
    #ports:
    #  - '${C_NODE1_EXP_PORT}:9042'
    #  - 7000:7000
